//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent_of_code.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Input2021 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Input2021() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent_of_code.Resources.Input2021", typeof(Input2021).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 119
        ///121
        ///129
        ///128
        ///130
        ///134
        ///138
        ///143
        ///113
        ///114
        ///129
        ///103
        ///90
        ///98
        ///91
        ///96
        ///101
        ///90
        ///73
        ///66
        ///74
        ///82
        ///80
        ///91
        ///92
        ///93
        ///96
        ///101
        ///102
        ///115
        ///122
        ///114
        ///119
        ///120
        ///108
        ///104
        ///109
        ///135
        ///123
        ///133
        ///134
        ///133
        ///138
        ///144
        ///151
        ///158
        ///159
        ///162
        ///166
        ///146
        ///137
        ///124
        ///153
        ///150
        ///153
        ///162
        ///169
        ///167
        ///169
        ///168
        ///162
        ///165
        ///138
        ///112
        ///111
        ///121
        ///122
        ///123
        ///130
        ///127
        ///135
        ///138
        ///136
        ///138
        ///141
        ///139
        ///144
        ///169
        ///174
        ///180
        ///183
        ///207
        ///210
        ///227
        ///224
        ///235
        ///239
        ///228
        ///232
        ///231
        ///238
        ///250
        ///260
        ///262
        ///264
        ///267
        ///276
        ///277
        ///283
        ///284
        ///285
        ///283
        ///280
        ///260
        ///259
        ///2 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
    }
}
