//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent_of_code.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Input2021 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Input2021() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent_of_code.Resources.Input2021", typeof(Input2021).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 119
        ///121
        ///129
        ///128
        ///130
        ///134
        ///138
        ///143
        ///113
        ///114
        ///129
        ///103
        ///90
        ///98
        ///91
        ///96
        ///101
        ///90
        ///73
        ///66
        ///74
        ///82
        ///80
        ///91
        ///92
        ///93
        ///96
        ///101
        ///102
        ///115
        ///122
        ///114
        ///119
        ///120
        ///108
        ///104
        ///109
        ///135
        ///123
        ///133
        ///134
        ///133
        ///138
        ///144
        ///151
        ///158
        ///159
        ///162
        ///166
        ///146
        ///137
        ///124
        ///153
        ///150
        ///153
        ///162
        ///169
        ///167
        ///169
        ///168
        ///162
        ///165
        ///138
        ///112
        ///111
        ///121
        ///122
        ///123
        ///130
        ///127
        ///135
        ///138
        ///136
        ///138
        ///141
        ///139
        ///144
        ///169
        ///174
        ///180
        ///183
        ///207
        ///210
        ///227
        ///224
        ///235
        ///239
        ///228
        ///232
        ///231
        ///238
        ///250
        ///260
        ///262
        ///264
        ///267
        ///276
        ///277
        ///283
        ///284
        ///285
        ///283
        ///280
        ///260
        ///259
        ///2 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {&lt;&lt;{({[(&lt;&lt;((({&lt;&gt;{}}(&lt;&gt;[]))&lt;{&lt;&gt;{}}&lt;[][]&gt;&gt;)([[[][]]][{{}&lt;&gt;}]))&gt;{(([&lt;{}&gt;{{}&lt;&gt;]][[&lt;&gt;()](&lt;&gt;&lt;&gt;)]))&lt;&lt;&lt;[[][]][[]
        ///{[([{[[[{({&lt;&lt;[&lt;&gt;[]]&lt;()[]&gt;&gt;(&lt;[]&lt;&gt;&gt;({}))&gt;&lt;{[{}()]{&lt;&gt;{}}}&lt;&lt;{}{}&gt;{{}[]}&gt;&gt;}&lt;&lt;{{&lt;&gt;()}&lt;()()&gt;}&lt;[(){}]&lt;[]{
        ///&lt;(((&lt;([(&lt;(&lt;&lt;[&lt;[][]&gt;&lt;{}{}&gt;]&gt;&gt;)&gt;&lt;(({[({}[])&lt;[]()&gt;][&lt;[]()&gt;&lt;{}{}&gt;]}({[{}&lt;&gt;][{}()]}{({}[])}))(&lt;[{{}[]
        ///{{&lt;[[([{({(&lt;[{()()}{{}&lt;&gt;}]({()()})&gt;){&lt;({[]&lt;&gt;}({}())){(()&lt;&gt;)&lt;[]&lt;&gt;&gt;}&gt;&lt;({()[]}{[]}){{{}{}}}&gt;}})}&lt;[[((([&lt;&gt;()
        ///[[({&lt;&lt;([[(({([()[]]{()&lt;&gt;})&lt;{&lt;&gt;[]}[{}()]&gt;}({{[]()}{[][]}}&lt;&lt;&lt;&gt;{}&gt;{()[]}&gt;))[(([(){}])&lt;&lt;(){}&gt;{&lt;&gt;
        ///({{{{[{[{ [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input10 {
            get {
                return ResourceManager.GetString("Input10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2264552475
        ///7681287325
        ///3878781441
        ///6868471776
        ///7175255555
        ///7517441253
        ///3513418848
        ///4628736747
        ///1133155762
        ///8816621663.
        /// </summary>
        internal static string Input11 {
            get {
                return ResourceManager.GetString("Input11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à kc-qy
        ///qy-FN
        ///kc-ZP
        ///end-FN
        ///li-ZP
        ///yc-start
        ///end-qy
        ///yc-ZP
        ///wx-ZP
        ///qy-li
        ///yc-li
        ///yc-wx
        ///kc-FN
        ///FN-li
        ///li-wx
        ///kc-wx
        ///ZP-start
        ///li-kc
        ///qy-nv
        ///ZP-qy
        ///nv-xr
        ///wx-start
        ///end-nv
        ///kc-nv
        ///nv-XQ.
        /// </summary>
        internal static string Input12 {
            get {
                return ResourceManager.GetString("Input12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 23,123
        ///1116,117
        ///60,18
        ///954,323
        ///1235,226
        ///1123,599
        ///862,231
        ///808,11
        ///982,687
        ///574,248
        ///1041,449
        ///584,105
        ///408,575
        ///594,466
        ///1058,677
        ///23,33
        ///127,862
        ///1305,367
        ///87,220
        ///194,855
        ///706,455
        ///550,241
        ///750,493
        ///922,616
        ///88,861
        ///682,822
        ///487,359
        ///1208,555
        ///579,674
        ///1097,266
        ///1042,400
        ///1043,712
        ///567,151
        ///328,694
        ///494,47
        ///1,623
        ///716,779
        ///574,198
        ///599,890
        ///63,532
        ///818,728
        ///1148,239
        ///104,848
        ///1062,47
        ///1185,516
        ///428,849
        ///1134,519
        ///472,866
        ///1146,207
        ///785,541
        ///75,668
        ///636,306
        ///554,512
        ///644,362
        ///795,623
        ///263,810
        ///805,0
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input13 {
            get {
                return ResourceManager.GetString("Input13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SHHNCOPHONHFBVNKCFFC
        ///
        ///HH -&gt; K
        ///PS -&gt; P
        ///BV -&gt; H
        ///HB -&gt; H
        ///CK -&gt; F
        ///FN -&gt; B
        ///PV -&gt; S
        ///KK -&gt; F
        ///OF -&gt; C
        ///SF -&gt; B
        ///KB -&gt; S
        ///HO -&gt; O
        ///NH -&gt; N
        ///ON -&gt; V
        ///VF -&gt; K
        ///VP -&gt; K
        ///PH -&gt; K
        ///FF -&gt; V
        ///OV -&gt; N
        ///BO -&gt; K
        ///PO -&gt; S
        ///CH -&gt; N
        ///FO -&gt; V
        ///FB -&gt; H
        ///FV -&gt; N
        ///FK -&gt; S
        ///VC -&gt; V
        ///CP -&gt; K
        ///CO -&gt; K
        ///SV -&gt; N
        ///PP -&gt; B
        ///BS -&gt; P
        ///VS -&gt; C
        ///HV -&gt; H
        ///NN -&gt; F
        ///NK -&gt; C
        ///PC -&gt; V
        ///HS -&gt; S
        ///FS -&gt; S
        ///OB -&gt; S
        ///VV -&gt; N
        ///VO -&gt; P
        ///KV -&gt; F
        ///SK -&gt; O
        ///BC -&gt; P
        ///BP -&gt; F
        ///NS -&gt; P
        ///SN -&gt; S
        ///NC -&gt; N
        ///FC -&gt; V
        ///CN -&gt; S
        ///OK -&gt; B
        ///SC -&gt; N
        ///HN -&gt; B
        ///HP [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input14 {
            get {
                return ResourceManager.GetString("Input14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à forward 8
        ///down 9
        ///forward 2
        ///down 1
        ///forward 9
        ///forward 7
        ///forward 5
        ///up 3
        ///up 3
        ///down 5
        ///forward 2
        ///down 8
        ///down 3
        ///forward 6
        ///down 2
        ///down 4
        ///down 7
        ///down 7
        ///forward 2
        ///down 6
        ///down 8
        ///down 2
        ///down 8
        ///up 9
        ///down 8
        ///forward 8
        ///down 5
        ///up 4
        ///forward 4
        ///forward 4
        ///forward 3
        ///down 9
        ///forward 8
        ///up 3
        ///forward 2
        ///forward 3
        ///forward 6
        ///down 7
        ///down 2
        ///forward 4
        ///forward 7
        ///forward 6
        ///up 5
        ///up 1
        ///forward 4
        ///down 9
        ///up 6
        ///forward 6
        ///up 9
        ///forward 1
        ///down 9
        ///forward 4
        ///down 3
        ///forward 7
        ///forward 5
        ///down 1
        ///up 9
        ///d [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input2 {
            get {
                return ResourceManager.GetString("Input2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 111011001010
        ///010011101110
        ///110001001010
        ///001101011101
        ///110100000011
        ///010110110010
        ///101000110110
        ///010100000011
        ///111001101111
        ///111001100011
        ///000110000100
        ///111011110100
        ///010001100000
        ///100011000010
        ///001001111010
        ///101001010010
        ///110000111010
        ///011100110101
        ///010111101111
        ///100011001001
        ///011110100001
        ///011101110110
        ///001011111001
        ///001110010100
        ///100001001000
        ///000100110111
        ///011111110010
        ///010101110011
        ///001101011100
        ///100001110101
        ///111000100000
        ///010111001010
        ///110000001010
        ///101011110100
        ///101010011111
        ///011001001000
        ///01001010 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input3 {
            get {
                return ResourceManager.GetString("Input3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 25,8,32,53,22,94,55,80,33,4,63,14,60,95,31,89,30,5,47,66,84,70,17,74,99,82,21,35,64,2,76,9,90,56,78,28,51,86,49,98,29,96,23,58,52,75,41,50,13,72,92,83,62,37,18,11,34,71,91,85,27,12,24,73,7,77,10,93,15,61,3,46,16,97,1,57,65,40,0,48,69,6,20,68,19,45,42,79,88,44,26,38,36,54,81,59,43,87,39,67
        ///
        ///25 83 15 27 22
        ///97 81 12 80 52
        ///65 58 91 23 36
        ///77 60 49 43 95
        ///13 21 56 78 99
        ///
        ///43 85 82 52 40
        ///19 14 91  4  7
        /// 6 87 64 26 56
        ///94 58 81 98 90
        ///18 72 23 37 20
        ///
        /// 5 43 13 47 93
        ///25 78 64 56 10
        ///75 90 50 72 14
        /// 9 29 5 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input4 {
            get {
                return ResourceManager.GetString("Input4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 580,438 -&gt; 580,817
        ///220,987 -&gt; 199,966
        ///300,674 -&gt; 300,523
        ///27,362 -&gt; 27,932
        ///890,430 -&gt; 854,430
        ///488,202 -&gt; 488,885
        ///824,930 -&gt; 824,740
        ///208,756 -&gt; 851,113
        ///967,288 -&gt; 967,960
        ///700,139 -&gt; 531,139
        ///671,463 -&gt; 671,150
        ///270,954 -&gt; 270,801
        ///682,718 -&gt; 682,146
        ///849,837 -&gt; 353,341
        ///779,635 -&gt; 420,635
        ///228,872 -&gt; 228,419
        ///34,76 -&gt; 745,787
        ///180,548 -&gt; 180,969
        ///429,668 -&gt; 445,652
        ///601,11 -&gt; 893,11
        ///400,314 -&gt; 128,586
        ///120,80 -&gt; 972,932
        ///133,144 -&gt; 969,980
        ///987,15 -&gt; 106,896
        ///940,676 -&gt; 940,322
        ///471,490 -&gt; 900,490
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input5 {
            get {
                return ResourceManager.GetString("Input5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4,3,4,5,2,1,1,5,5,3,3,1,5,1,4,2,2,3,1,5,1,4,1,2,3,4,1,4,1,5,2,1,1,3,3,5,1,1,1,1,4,5,1,2,1,2,1,1,1,5,3,3,1,1,1,1,2,4,2,1,2,3,2,5,3,5,3,1,5,4,5,4,4,4,1,1,2,1,3,1,1,4,2,1,2,1,2,5,4,2,4,2,2,4,2,2,5,1,2,1,2,1,4,4,4,3,2,1,2,4,3,5,1,1,3,4,2,3,3,5,3,1,4,1,1,1,1,2,3,2,1,1,5,5,1,5,2,1,4,4,4,3,2,2,1,2,1,5,1,4,4,1,1,4,1,4,2,4,3,1,4,1,4,2,1,5,1,1,1,3,2,4,1,1,4,1,4,3,1,5,3,3,3,4,1,1,3,1,3,4,1,4,5,1,4,1,2,2,1,3,3,5,3,2,5,1,1,5,1,5,1,4,4,3,1,5,5,2,2,4,1,1,2,1,2,1,4,3,5,5,2,3,4,1,4,2,4,4,1,4,1,1,4,2,4,1,2,1,1,1,1,1,1,3,1,3, [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input6 {
            get {
                return ResourceManager.GetString("Input6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1101,1,29,67,1102,0,1,65,1008,65,35,66,1005,66,28,1,67,65,20,4,0,1001,65,1,65,1106,0,8,99,35,67,101,99,105,32,110,39,101,115,116,32,112,97,115,32,117,110,101,32,105,110,116,99,111,100,101,32,112,114,111,103,114,97,109,10,1425,266,740,842,335,1076,1125,108,728,131,553,757,316,361,475,1058,555,157,37,1501,287,61,22,394,886,535,235,734,1381,428,200,838,84,0,99,397,516,1260,1079,457,685,669,85,1161,851,1413,207,125,23,396,1024,637,712,942,320,507,32,686,1073,449,736,619,120,1092,674,769,519,26,42,366,187,261,38 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input7 {
            get {
                return ResourceManager.GetString("Input7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à dac abcf ac fdbcga dgcbae gcbfde fgcbd agfed adcgf cdbgfea | cbfa bcafdg cbfa bafcgd
        ///abfgd baedc feb fgde fbagcd facbdge agcbfe bgafde fe ebdfa | bef fe dgfe feb
        ///dfc dc afegbc bcafe fcead agefd cafdeb fcbeadg cbed cabdfg | cd geadf cfd bfaec
        ///efacdgb abefdg efagbc af afe gdeab dbfa dgefa acegbd cdegf | cfdge gefda ecbgdfa eaf
        ///feg gdbea edgbca gefdab caefdbg egfda afdgc fe cgfdeb efba | edafbg bdefgc egdfa gbead
        ///bfeac becfd cbgdf gfabed gdefcab dcae edb de bgfaec fdeabc | bcfdg eagbfd fedbc cefdb
        ///bgecd  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input8 {
            get {
                return ResourceManager.GetString("Input8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 8654434789432446987654321056789235678953245798764212456789656568977654232457898754567898765431335999
        ///8743125678931234599987643238993123567894345989542101234678943459865432101345789643479999878540129877
        ///9651056799320125678998764369895644678965956976543233458799202568986574519499996532445989998761298956
        ///6543234789632347899219865456789795789879899898754755567893212456998986798987897621234678979872987645
        ///7887645696543456799423989978998989893989767789865676679995343689879497986596789432349899865989876434
        ///89 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Input9 {
            get {
                return ResourceManager.GetString("Input9", resourceCulture);
            }
        }
    }
}
